In [1]:
import torch

In [3]:
m = 4
n = 5
a = torch.randint(0, 3, (m, 8)).float()
b = torch.randint(0, 3, (n, 8)).float()

a, b

(tensor([[1., 2., 2., 0., 2., 0., 0., 0.],
         [1., 2., 0., 2., 2., 1., 0., 0.],
         [2., 2., 1., 2., 1., 1., 0., 1.],
         [2., 0., 0., 2., 0., 2., 1., 1.]]),
 tensor([[1., 2., 1., 2., 2., 0., 1., 2.],
         [2., 1., 0., 2., 1., 2., 0., 0.],
         [2., 1., 2., 1., 2., 2., 1., 2.],
         [1., 0., 1., 2., 1., 0., 0., 2.],
         [0., 2., 2., 2., 0., 1., 0., 1.]]))

In [19]:
def cos_sim_matrix(
    a: torch.Tensor,
    b: torch.Tensor,
    eps: float = 1e-8
) -> torch.Tensor:
    a_norm = a.norm(dim=1)[..., None]
    b_norm = b.norm(dim=1)[..., None]

    a_ = a / torch.clamp(a_norm, min=eps)
    b_ = b / torch.clamp(b_norm, min=eps)

    sim_matrix = torch.mm(a_, b_.T)

    return sim_matrix

cos_sim_matrix(a, b)

tensor([[0.6999, 0.4447, 0.6940, 0.4181, 0.5930],
        [0.7971, 0.8571, 0.6687, 0.5641, 0.6429],
        [0.8603, 0.8686, 0.8341, 0.7538, 0.8018],
        [0.5518, 0.8571, 0.7245, 0.6447, 0.5000]])

In [24]:
import numpy as np

from scipy.optimize import linear_sum_assignment

cost_matrix = np.random.random((0, 0))

linear_sum_assignment(cost_matrix)

t = torch.empty((0, 0)) 
t

tensor([], size=(0, 0))

In [25]:
from torch.nn.functional import cosine_similarity

sim_rows = []
for a_ in a:
    sim_row = ", ".join(f"{cosine_similarity(a_, b_, 0).item():.4f}" for b_ in b)
    sim_rows.append(sim_row)
print("\n".join(sim_rows))

0.6999, 0.4447, 0.6940, 0.4181, 0.5930
0.7971, 0.8571, 0.6687, 0.5641, 0.6429
0.8603, 0.8686, 0.8341, 0.7538, 0.8018
0.5518, 0.8571, 0.7245, 0.6447, 0.5000


In [28]:
emb = [torch.rand((1, 2048)) for _ in range(10)]
emb = torch.cat(emb, dim=0)
emb.shape

torch.Size([10, 2048])

In [33]:
t = torch.rand((10,))
a, = torch.where(t > .5)
a

tensor([0, 3, 4, 6, 8, 9])